# Generated by Django 5.1.7 on 2025-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Name', models.CharField(max_length=36)),
                ('DOB', models.DateField()),
                ('Aadhar', models.BigIntegerField()),
                ('Pan', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Account_no', models.BigAutoField(default=1234567890, primary_key=True, serialize=False)),
                ('Pin', models.IntegerField(default=0)),
                ('Balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7)),
                ('OTP', models.IntegerField(default=0)),
                ('email', models.EmailField(default='saichiraboina14@gmail.com', max_length=254)),
            ],
        ),
    ]
