# Generated by Django 5.1.7 on 2025-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_no',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
